name: workshop_manager
description: "Aplikasi Workshop Manager dan Kasir untuk Bengkel"
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  path: ^1.8.3
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  flutter_slidable: ^4.0.3
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0
  lottie: ^3.3.2
  flutter_bluetooth_printer: ^2.0.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.5
  pdf: ^3.11.0
  printing: ^5.13.0
  supabase_flutter: ^2.8.3
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/school.json
    - assets/teamwork.json
